run-shell "powerline-daemon -q"

run-shell "tmux source-file $(python -c 'import site; print(site.getsitepackages()[0])')/powerline/bindings/tmux/powerline.conf"

# Start numbering at 1
set -g base-index 1

# reload config
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

# utf8 support
#set-window-option -g utf8 on

# Set the keybinding to Control-s
set -g prefix C-s
