#!/bin/bash

BASE_DIR="$(realpath $(dirname "$0"))"

source "$BASE_DIR/lib/base"
source "$BASE_DIR/lib/env"
source "$BASE_DIR/lib/fs"

function main() {
    echo "QuackaTech dotfiles installer"
    echo

    if [ "$force" == "1" ]
    then
        echo
        echo "###############################################"
        echo "# Warning: use of lethal force is authorized! #"
        echo "###############################################"
        echo
        
        sleep 3
    fi

    # Initialize config variables
    init_variables

    # Set up dotfiles
    setup git

    echo "Thank you for using the QuackaTech dotfiles installer"
    echo "We hope you'll have a pleasant day"
    echo
}

force="0"

while getopts "n:e:fh" opt; do
    case $opt in
        n)
            full_name="$OPTARG"
            ;;
        e)
            email="$OPTARG"
            ;;
        f) 
            force="1"
            ;;
        h)
            print_help
            exit 0
            ;;
        ?)
            print_help
            exit 1
            ;;
    esac
done

main
