#!/bin/bash

BASE_DIR="$(realpath $(dirname "$0"))"

sections=(git nvim tmux)

source "$BASE_DIR/lib/env"
source "$BASE_DIR/lib/base"
source "$BASE_DIR/lib/fs"
source "$BASE_DIR/lib/main"

main 

# vim: syntax=sh
