# action motion [finger_count] command
#
# where action and motion is either:
#     swipe up
#     swipe down
#     swipe left
#     swipe right
#     pinch in
#     pinch out

# Browser go back
gesture: swipe right 2  xdotool key alt+Left

# Browser go forward
gesture: swipe left 2   xdotool key alt+Right

# Go to next/prev workspace
gesture: swipe left 4   bspc desktop -f next
gesture: swipe right 4   bspc desktop -f prev
